### ISSUE TITLE
Some features request

### ISSUE THREAD

**Issue by rafaelcn** [dr-Styki/ScreenRec#10]
The screen record is quite awesome but I will drop some features that might be good to include in the application.

- [ ] Record what keys are being pressed as well
- [ ] Ability to highlight mouse pointer, either with a circle or some colour.

Those might be some switches that could be inserted in the app.

**Comment by dr-Styki** [comment]
I dunno, record what keys are being pressed could be useful but there is some problemes with that. 

- Wayland prevent that sort of things. So the feature will be unmaintenable in the future.
- How to prevent the app to show typed password ?
- Not a lot of free time actualy and I want to focus on video hardware acceleration support and some others things

As a workarround, screenkey app already provide this feature but as I said above don't work on wayland.

**Comment by dr-Styki** [comment]
For the mouse pointer highlighting, that's could be cool. But there is already some elementary OS features which can help like the mouse pointer size and reveal pointer options. I have to think about that.

**Comment by rafaelcn** [comment]
I didn't know that Wayland does not allow this kind of behaviour, although something should/could be done because there are some nice usages of this feature. 

For the second point, you should not worry about that. This sure could be something to be implemented but if the user is recording with this feature enabled he should be aware that the typed password will be displayed unless edited out of the video after the recording. 

I can understand your lack of free time. This is a very valid point. After discussing all of this I think this issue is solved and you can add the mouse pointer highlight to a future milestone.
