### ISSUE TITLE
Twitter Refuses to take this video

### ISSUE THREAD

**Issue by shubhamthedev** [dr-Styki/ScreenRec#14]
![Screenshot from 2020-06-08 21-54-57](https://user-images.githubusercontent.com/33488761/84055631-bd289080-a9d2-11ea-8389-83cb73fbb20e.png)

**Comment by dr-Styki** [comment]
After a look at [developer.twitter.com](https://developer.twitter.com/en/docs/media/upload-media/uploading-media/media-best-practices) it seems that twitter only support YUV4:2:0 while ScreenRec record videos in YUV 4:4:4. I will look at the Gstreamer doc to use YUV 4:2:0 instead in the next release.

Thanks for openning this issue

**Comment by ghost** [comment]
Ah, that explains a lot now.

**Comment by Hedronmx** [comment]
Whatsapp also refuses to play the video on mobile

**Comment by dr-Styki** [comment]
Fixed in the PR 4524625
