### ISSUE TITLE
Travis CI not configured

### ISSUE THREAD

**Issue by NathanBnm** [dr-Styki/ScreenRec#17]
It seems that you have the `travis.yml` file but your repository is not configured to run with Travis CI.

When checking https://travis-ci.com/github/dr-styki/screenrec it seems that your repository has not been registered on Travis CI.

You have to register your repository on Travis CI in order to make it work.

You can read more about it here https://github.com/elementary/houston/wiki/Continuous-Integration

_Note: The Node version has to remain `10.17.0` instead of `lts/*` in order to make it work (see elementary/houston#773 for further info)_

**Comment by dr-Styki** [comment]
That's ok for Travis, Thanks.
