### ISSUE TITLE
Segmentation fault on stop recording

### ISSUE THREAD

**Issue by tetebueno** [dr-Styki/ScreenRec#22]
Start recording screen with the following parameters:

![image](https://user-images.githubusercontent.com/9064236/85895583-57f3de00-b7cd-11ea-803c-622da598f5e5.png)

Grab area, wait for something to get recorded, when "stop recording" button is pressed application shuts down and console displays:

```
$ com.github.dr-styki.screenrec 

(com.github.dr-styki.screenrec:668): Gdk-CRITICAL **: 16:36:06.557: gdk_visual_get_screen: assertion 'GDK_IS_VISUAL (visual)' failed

(com.github.dr-styki.screenrec:668): Gdk-CRITICAL **: 16:36:06.557: gdk_window_new: assertion 'gdk_visual_get_screen (attributes->visual) == screen' failed

(com.github.dr-styki.screenrec:668): Gdk-CRITICAL **: 16:36:06.557: gdk_window_get_width: assertion 'GDK_IS_WINDOW (window)' failed

(com.github.dr-styki.screenrec:668): Gdk-CRITICAL **: 16:36:06.557: gdk_window_get_height: assertion 'GDK_IS_WINDOW (window)' failed
Segmentation fault
```

Is there a way to get more debug information?

Here's some system information:

![image](https://user-images.githubusercontent.com/9064236/85895748-9e493d00-b7cd-11ea-92e7-b670b757554f.png)

**Comment by dr-Styki** [comment]
Hi, that's weird. I can't reproduce the bug neither on elementary OS nor on Archlinux. 

To get more debug information you can use :

- G_MESSAGES_DEBUG=all com.github.dr-styki.screenrec for GTK related info.    
- GST_DEBUG=5 ./com.github.dr-styki.screenrec for Gstreamer related info.

Did you get the same bug on an elementary OS clean install ?

**Comment by tetebueno** [comment]
Hi, one thing maybe worth noting is that the same happens with https://github.com/mohelm97/screenrecorder, maybe both share same libraries and that's where I should be looking at.

> * G_MESSAGES_DEBUG=all com.github.dr-styki.screenrec for GTK related info.
> * GST_DEBUG=5 ./com.github.dr-styki.screenrec for Gstreamer related info.

I'll try this.

> Did you get the same bug on an elementary OS clean install ?

Nope, I'll give this a try too.

Cheers.

**Comment by tetebueno** [comment]
Hi, I was finally about to make some tests but realized this has been fixed. Either I unbroke something else or this was fixed with a new release. Either way, this is closed, I don't think it's worth investigation.

Cheers.
