### ISSUE TITLE
Use Granite.markup_accel_tooltip for keyboard shortcuts

### ISSUE THREAD

**Issue by cassidyjames** [dr-Styki/ScreenRec#31]
i.e. the "Save" shortcut would be better formatted. See: https://valadoc.org/granite/Granite.markup_accel_tooltip.html

https://github.com/dr-Styki/ScreenRec/blob/1e14c8e35a205a1fc0f45797cf264d748ceada75/src/ScreenrecorderWindow.vala#L314

https://github.com/dr-Styki/ScreenRec/blob/1e14c8e35a205a1fc0f45797cf264d748ceada75/src/ScreenrecorderWindow.vala#L319-L320

**Comment by dr-Styki** [comment]
Fixed in the commit 49694b889d22805f8ed0fc8eea910ebbd9adb8ca thanks for the information.
