### ISSUE TITLE
Pronlem with audio

### ISSUE THREAD

**Issue by ghost** [dr-Styki/ScreenRec#32]
Dear Developer,
I need your help, I downloaded your app and discovered that despite having increased the volume on my recorded videos at the highest level, I can barely hear anything.

Could you please help me?

Best wishes,

Michael Plotegher

https://user-images.githubusercontent.com/54290469/114284069-a10bda80-9a4d-11eb-8931-4dcac47a7179.mp4

**Comment by dr-Styki** [comment]
Hi @michael1999crypto 
That's weird because ScreenRec doesn't interacte with the volume control. Can you install `pavucontrol` and look at the `Recording` tab while recording to see if the recording volume is at 100% ?
![Screenshot from 2021-04-17 19-50-41](https://user-images.githubusercontent.com/63053131/115122402-16c8f680-9fb8-11eb-97fc-df586bfa912f.png)

**Comment by krcx** [comment]
Hi, I was having the same problem, it suddenly stopped recording with audio. I came here looking for a solution. Then I downloaded `pavucontrol` and for some reason my speakers didn't look like they are working(but I was hearing perfectly fine) in the app. After fiddling every setting and then turning them back to defaults, I muted my microphone from pulseaudio and then I opened it back from the wingpanel and it fixed the problem! But I am not sure if that counts as a solution haha. 

Thanks for this lovely app!

edit: video keeps dying:(

**Comment by dr-Styki** [comment]
Hi @krcx  what do you mean by 'video keeps dying:(' ?

**Comment by krcx** [comment]
Hi @dr-Styki I was trying to add a video to show how it got fixed suddenly. I was randomly changing the settings and unchanging them again to their default values while recording and it suddenly fixed the problem. But when I uploaded, video only showed white screen for some reason (sound is fine though) so I deleted it. You can see from the edits that I added/deleted the video. (Also you can click that links to reach to the broken video.)

**Comment by dr-Styki** [comment]
Ah yes ! I can see the video. Nice theme :)
