### ISSUE TITLE
Not working on elementary os 6

### ISSUE THREAD

**Issue by andirsun** [dr-Styki/ScreenRec#40]
I really like your app and I want to use it on elementary 6 but After compile and test on elementary os 6 stable release, the files saved after record the screen are corrupted no matter what video format I select.

![Screenshot from 2021-08-12 15-11-02](https://user-images.githubusercontent.com/22928302/129263001-4188be6c-97e9-4c5b-8341-59099cb8d396.png)

**Comment by dr-Styki** [comment]
Hi, I just tried it and it works. Have you installed the dependencies listed in debian/control ? (ffmpeg, gstreamer1.0-plugins-ugly, gstreamer1.0-libav, gstreamer1.0-plugins-good)
