### ISSUE TITLE
Screenshot URLs don't seem to be valid

### ISSUE THREAD

**Issue by danirabbit** [dr-Styki/ScreenRec#47]
While reviewing your app I noticed that it doesn't seem like the URLs for your screenshots are valid and the ones shown in your README on GitHub appear to be out of date

**Comment by dr-Styki** [comment]
Fix by 0a264f169375d7b42dbc866ead4b9a6e90ae78c0 and 1076a99354de37f4e0efac268f72cba08881f0a1
