### ISSUE TITLE
Don't bundle plugins

### ISSUE THREAD

**Issue by danirabbit** [dr-Styki/ScreenRec#48]
While reviewing your app for AppCenter I noticed that you're bundling gstreamer plugins and video codecs. These should come from the system for security reasons

**Comment by dr-Styki** [comment]
Unfortunately without the plugin MP4 recording doesn't work.

**Comment by ryonakano** [comment]
Looks like the ugly plugin is used only for [`x264enc`](https://gstreamer.freedesktop.org/documentation/x264/index.html). What about using [`avenc_mpeg4`](https://gstreamer.freedesktop.org/documentation/libav/avenc_mpeg4.html) instead?

**Comment by dr-Styki** [comment]
Yep, I use gstreamer1-plugins-ugly only for x264enc. I don't use avenc_mpeg4 because it relies on ffmpeg and I want to avoid that. Also, I would like to add support for hardware encoding in the future and 'll need to add gstreamer-vaapi the same way. So for me that's not realy an issue 😥️

**Comment by dr-Styki** [comment]
Being mandatory for the app to work, I close the issue.
