### ISSUE TITLE
Problem 

### ISSUE THREAD

**Issue by aliceemanueli** [dr-Styki/ScreenRec#53]
Hello good night, I am having serious problems installing the App as described here on this page, there are several errors in the command terminal, I feel frustrated and I really need this App, please consider bringing it to the app center because it is very useful and of utmost importance to me!  Thank you!

**Comment by ChildishGiant** [comment]
What are the errors?

**Comment by dr-Styki** [comment]
ScreenRec has been approved to be published in the appcenter, it should be availble soon. 🙂️
