### ISSUE TITLE
Change required for AppCenter: Name in use

### ISSUE THREAD

**Issue by cassidyjames** [dr-Styki/ScreenRec#8]
Thanks for submitting your app to AppCenter! However, while reviewing the submission, we found an issue that needs to be resolved.

Your app is named "Screen Recorder," but that name is already in use on AppCenter. As noted in the [Publishing Requirements](https://docs.elementary.io/develop/appcenter/publishing-requirements#naming):

>To protect both users and developers, your app's name must not be the same as or confusingly similar to an existing app in AppCenter or other brand, as determined by app reviewers.

Please change the name in the following user-facing locations:
- AppData
  https://github.com/dr-Styki/ScreenRec/blob/8c090c17b2a8e839862b1dd608bf6d8dc85bdd58/data/com.github.dr-styki.screenrec.appdata.xml.in#L8
- .desktop file
  https://github.com/dr-Styki/ScreenRec/blob/8c090c17b2a8e839862b1dd608bf6d8dc85bdd58/data/com.github.dr-styki.screenrec.desktop.in#L2

Note that you **do not** need to update your app's GitHub name, RDNN, README, etc. as these are not considered user-facing.

Once you've made the requested changes, create a new release on GitHub and re-submit it to the [AppCenter Dashboard](https://developer.elementary.io). As always, if you have any questions you can reply here.

**Comment by dr-Styki** [comment]
My bad. I've change back the app name to ScreenRec and re-submit it.

Thanks for letting me know about it.
