### ISSUE TITLE
[Suggestion] Add Actions

### ISSUE THREAD

**Issue by ghost** [dr-Styki/ScreenRec#9]
[Imgur](https://imgur.com/KFdJR11)

I think it would be nice to have more actions added to the `.desktop` file, so when right clicking on ScreenRec from the dock, there are option for quicker access. This should be easy to pull off.

**Comment by JayXT** [comment]
Yes, I think it would be a great addition to already nice and handy app.

**Comment by dr-Styki** [comment]
Yes, I think about a static quicklist like the screenshot tool one.
- [Record the whole screen]
- [Record the current Window]
- [Record the selected Area]

And a dynamic quicklist with [Cancel/Pause/Resume] and [Stop] actions.
- [Cancel/Pause/Resume]
- [Stop]

But I'm asking myself if that can't be confusing for the end user to see the 3 recording actions while the app already record ?

**Comment by JayXT** [comment]
I'd say that dynamic list looks more promising and clear, since the list of menu items will be contextual. It could have such options:
- Record or Pause (depending on recording state).
- Stop (available when recording started)

In case of Record/Pause action, for simplicity sake it could use the last recording mode with all of its settings. 
However, I'm not sure what would be better when clicking Stop:
- To open standard saving screen.
- To save file silently.

The last option makes app usage very simple, especially when you have to record screen quite often.

**Comment by JayXT** [comment]
Nonetheless, on second thought, the cancel option, you've mentioned, might be useful as well, so basically the list of menu items could be in several possible states:
1) No recording is running:
- Record
2) The app is recording:
- Pause
- Cancel
- Stop
3) The recording was put on pause:
- Continue
- Cancel
- Stop

**Comment by dr-Styki** [comment]
There is also the cancelable countdown which can use the cancel button.

**Comment by dr-Styki** [comment]
I've add a static quicklist for now, but i'm unable to get a dynamic quicklist working. Even with the code example from [LauncherAPI](https://wiki.ubuntu.com/Unity/LauncherAPI#Vala_Example). 

No issues with progress bar and badge counter. But no dynamic quicklist :disappointed:

If someone know an elementary OS app that use a dynamic quicklist. Feel free to share the app name.

**Comment by JayXT** [comment]
Hmm... Although such apps probably exist, I'm not aware of them. Could it be that there was some conflict between static and dynamic lists? For example, you've tried to use dynamic list when .desktop file had static entries.

**Comment by dr-Styki** [comment]
Nop, no conflict between static and dynamic lists. And with dbus-monitor a can see the dbus quicklist message. So I dunno. :(

In my memories files had a dynamic quicklist which shows favorites folders. And right now it doesn't show the quicklist. So is the quicklist features still working in eOS ? =/

**Comment by dr-Styki** [comment]
In my memories files had a dynamic quicklist which shows favorites folders. And right now it doesn't show the quicklist. So is the quicklist features still working in eOS ? =/

**Comment by dr-Styki** [comment]
After some tests it looks like the dynamic quicklist feature not longer work in elementary OS 5.x.x. I tested the same code on Loki and it works. So I've open a new issue, now we have to wait.
https://github.com/elementary/dock/issues/53#issue-638124728

**Comment by JayXT** [comment]
That's great! Let's wait until it's fixed.

**Comment by dr-Styki** [comment]
As the quicklist feature has been removed from the eOS documentation and is not implemented in Granite.Services.Application I close this issue. If the feature come back in the futur I'll happy to add a quicklist to ScreenRec.
